name: alga_parser
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  petitparser:
    git:
      url: https://github.com/petitparser/dart-petitparser

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
